server:
  port: 8080
spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
# mybatis
mybatis:
  type-aliases-package: com.caihao.shirodemo2.entity
  mapper-locations: classpath:mapper/**/*.xml